
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  engine: "classic",
  datasource: {
    // Migrations must run over the direct connection: Supabase's transaction
    // pooler (port 6543) does not support the prepared statements and advisory
    // locks the migration engine relies on.
    url: env("DIRECT_URL"),
  },
  migrations: {
    path: "prisma/migrations",
    // No seed: the only thing ever seeded was the test-login profile, and that
    // login is gone. Real profiles are created on first sign-in.
  },
});
