-- Remaps every remaining primary key to `Int GENERATED BY DEFAULT AS IDENTITY`,
-- so all seven models match Post and Author instead of splitting three ways
-- between uuid, cuid, and int.
--
-- WHAT MAKES THIS SAFE TO RUN AT ALL: no old id value is used as a fact by
-- anything outside the database. Member.id never leaves the server (no DTO
-- carries it, no route accepts it, nothing validates it as a uuid). Place.id and
-- Bookmark.id do reach the browser, but only inside a rendered page or a fetch
-- the same page just issued — nothing persists them. The exceptions are the two
-- signed cookies; see the PREREQUISITE below.
--
-- THE APPROACH: add a new int column beside each old key, populate it, then
-- point the foreign keys at it and drop the old one. NOT `ALTER COLUMN TYPE` —
-- there is no cast from uuid or from a cuid text value to int, and even for the
-- children a USING clause would have to re-derive the parent's new value per
-- row. Carrying an explicit mapping column is what lets the children be
-- rewritten by join instead of by guess.
--
-- Ordering is forced by the foreign keys: a child's new value cannot be
-- computed before its parent has one, and a parent's old column cannot be
-- dropped while a child still references it. Hence parents first
-- (Member, Place, Bookmark), then the columns that point at them.
--
-- NOT REVERSIBLE. The old uuid and cuid values are gone once the columns drop.
-- Recovering them means restoring a snapshot, not running a down migration —
-- take one before applying this against live data.
--
-- ===========================================================================
-- ONE PREREQUISITE, AND IT MUST BE DONE FIRST.
--
-- `Session` has to be empty before this runs. Its id is renumbered — nothing
-- references it, so the column is replaced outright — but that id is embedded
-- in a signed cookie which outlives this migration:
--
--   Session.id -> the session cookie, `<id>.<secret>`
--
-- A renumbered id leaves those cookies pointing at the wrong row, which is
-- worse than pointing at nothing: a cookie that resolves to another member's
-- session is an account takeover, not a logout. Emptying the table makes every
-- outstanding cookie resolve to nothing, which is the state the app already
-- handles (it is what a session sweep produces).
--
-- The secret half would still have to match, so this is not by itself an
-- exploitable path — but "the id names the wrong row" is not a property to
-- leave standing on the strength of a second check.
--
-- RECOMMENDED, NOT REQUIRED: empty `PhoneVerification` too. Its id rides in the
-- phone-challenge cookie the same way, so an in-flight challenge started before
-- the migration fails to parse afterwards and costs that user one more SMS.
-- Bounded by the cookie's 10-minute TTL. It is not enforced because the table
-- has no foreign key and its rows cannot affect the renumbering — see the guard
-- below. `PasswordAttempt` is in the same position and is pure rate-limit
-- bookkeeping; emptying it only widens a budget.
--
-- Emptying them removes rows, so it is NOT done here and NOT done by a script.
-- Every automated path is refused on purpose: the pre-tool hook rejects row
-- destruction in a migration — it refused this file twice while it was being
-- written, the second time for merely quoting the statements inside this
-- comment — and withDeleteGuard() rejects deleteMany from application code.
-- This repository's DATABASE_URL points at live Supabase.
--
-- Empty them by hand, after review, then apply this migration. The guard at the
-- end of the remap section refuses to proceed while `Session` still holds rows,
-- so forgetting that one cannot corrupt anything — it fails the migration while
-- every change so far is still additive and reversible.
--
-- All three are recoverable by their owners at no cost beyond inconvenience:
-- Session and PhoneVerification are re-created by signing in again, and
-- PasswordAttempt is rate-limit bookkeeping whose loss only widens a budget.
-- That is why they may be emptied at all, and it is the reason these three are
-- the models already listed in HARD_DELETE_ALLOWED.
--
-- SEQUENCING, which the guard makes safe rather than merely advised: signing in
-- writes a Session row, so a sign-in between emptying the table and applying
-- this file puts one back and the migration stops. Apply it first, then sign in.
-- The failure is loud and harmless, so getting this wrong costs one retry.
--
-- USER-VISIBLE FALLOUT: everyone signed in is logged out. Every first login is
-- SMS-gated, so re-entry is rate-limited (30s resend, 5/hour) — expect support
-- noise proportional to how many people were signed in.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Member. The parent of three cascading foreign keys.
--
-- Note this table had NO database default: ids came from the Prisma client
-- (`@default(uuid(4))`), a leftover from Supabase Auth issuing them. The new
-- column is an identity column, so generation moves into Postgres where the
-- other two int models already keep it.
-- ---------------------------------------------------------------------------

ALTER TABLE "Member" ADD COLUMN "id_int" INTEGER;

-- Deterministic order rather than arbitrary: oldest account gets 1. Nothing
-- depends on the numbering, but a stable rule makes the result reproducible if
-- this has to be re-derived on a restored snapshot.
WITH numbered AS (
  SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS n FROM "Member"
)
UPDATE "Member" m SET "id_int" = numbered.n FROM numbered WHERE m."id" = numbered."id";

-- ---------------------------------------------------------------------------
-- Place, Bookmark. Same shape, and both are parents of columns rewritten below.
-- ---------------------------------------------------------------------------

ALTER TABLE "Place" ADD COLUMN "id_int" INTEGER;
WITH numbered AS (
  SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS n FROM "Place"
)
UPDATE "Place" p SET "id_int" = numbered.n FROM numbered WHERE p."id" = numbered."id";

ALTER TABLE "Bookmark" ADD COLUMN "id_int" INTEGER;
WITH numbered AS (
  SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS n FROM "Bookmark"
)
UPDATE "Bookmark" b SET "id_int" = numbered.n FROM numbered WHERE b."id" = numbered."id";

-- ---------------------------------------------------------------------------
-- The referencing columns. Each is resolved by joining to its parent's mapping,
-- which is why the parents above keep both columns until this section is done.
-- ---------------------------------------------------------------------------

ALTER TABLE "Bookmark" ADD COLUMN "memberId_int" INTEGER;
UPDATE "Bookmark" b SET "memberId_int" = m."id_int" FROM "Member" m WHERE b."memberId" = m."id";

ALTER TABLE "Session" ADD COLUMN "memberId_int" INTEGER;
UPDATE "Session" s SET "memberId_int" = m."id_int" FROM "Member" m WHERE s."memberId" = m."id";

ALTER TABLE "AuthIdentity" ADD COLUMN "memberId_int" INTEGER;
UPDATE "AuthIdentity" a SET "memberId_int" = m."id_int" FROM "Member" m WHERE a."memberId" = m."id";

ALTER TABLE "PostPlace" ADD COLUMN "placeId_int" INTEGER;
UPDATE "PostPlace" pp SET "placeId_int" = p."id_int" FROM "Place" p WHERE pp."placeId" = p."id";

ALTER TABLE "BookmarkMemo" ADD COLUMN "placeId_int" INTEGER;
UPDATE "BookmarkMemo" bm SET "placeId_int" = p."id_int" FROM "Place" p WHERE bm."placeId" = p."id";

ALTER TABLE "BookmarkMemo" ADD COLUMN "bookmarkId_int" INTEGER;
UPDATE "BookmarkMemo" bm SET "bookmarkId_int" = b."id_int" FROM "Bookmark" b WHERE bm."bookmarkId" = b."id";

-- Refuse to continue on an unmapped row, and refuse to continue if the
-- PREREQUISITE above was skipped. Both would otherwise surface much later: an
-- unmapped row as a NOT NULL violation several statements down with nothing
-- pointing at the cause, and a non-empty Session table as silently mismatched
-- cookies after deploy. Everything before this point is additive, so failing
-- here leaves the schema usable and the old columns intact.
DO $$
DECLARE
  bad INTEGER;
  live INTEGER;
BEGIN
  SELECT
    (SELECT count(*) FROM "Member" WHERE "id_int" IS NULL)
  + (SELECT count(*) FROM "Place" WHERE "id_int" IS NULL)
  + (SELECT count(*) FROM "Bookmark" WHERE "id_int" IS NULL OR "memberId_int" IS NULL)
  + (SELECT count(*) FROM "Session" WHERE "memberId_int" IS NULL)
  + (SELECT count(*) FROM "AuthIdentity" WHERE "memberId_int" IS NULL)
  + (SELECT count(*) FROM "PostPlace" WHERE "placeId_int" IS NULL)
  + (SELECT count(*) FROM "BookmarkMemo" WHERE "placeId_int" IS NULL OR "bookmarkId_int" IS NULL)
  INTO bad;
  IF bad > 0 THEN
    RAISE EXCEPTION 'id remap incomplete: % unmapped row(s); aborting before any column is dropped', bad;
  END IF;

  -- Only Session is a hard requirement, and only because its id is renumbered
  -- while the cookie carrying that id stays in the browser. PhoneVerification
  -- and PasswordAttempt are deliberately NOT checked here: neither has a
  -- foreign key, so their rows are inert with respect to the renumbering, and
  -- refusing to run over them would fail the migration for something that
  -- cannot corrupt anything. Emptying them is still recommended (a stale
  -- challenge cookie costs one extra SMS for up to its 10-minute TTL), but it
  -- is a courtesy, not a precondition — and making it one would forbid the
  -- safest deploy order, where people are allowed to sign in again as soon as
  -- the migration has finished.
  SELECT count(*) FROM "Session" INTO live;
  IF live > 0 THEN
    RAISE EXCEPTION
      'Session must be empty before this migration (% row(s) found): its id is renumbered, and a cookie minted before that would resolve to a different member''s row. See the PREREQUISITE at the top of this file.', live;
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Drop the old foreign keys, primary keys, and the indexes on replaced columns.
-- ---------------------------------------------------------------------------

ALTER TABLE "Bookmark" DROP CONSTRAINT "Bookmark_memberId_fkey";
ALTER TABLE "Session" DROP CONSTRAINT "Session_memberId_fkey";
ALTER TABLE "AuthIdentity" DROP CONSTRAINT "AuthIdentity_memberId_fkey";
ALTER TABLE "PostPlace" DROP CONSTRAINT "PostPlace_placeId_fkey";
ALTER TABLE "BookmarkMemo" DROP CONSTRAINT "BookmarkMemo_placeId_fkey";
ALTER TABLE "BookmarkMemo" DROP CONSTRAINT "BookmarkMemo_bookmarkId_fkey";

ALTER TABLE "BookmarkMemo" DROP CONSTRAINT "BookmarkMemo_pkey";
ALTER TABLE "PostPlace" DROP CONSTRAINT "PostPlace_pkey";
ALTER TABLE "Bookmark" DROP CONSTRAINT "Bookmark_pkey";
ALTER TABLE "Place" DROP CONSTRAINT "Place_pkey";
ALTER TABLE "Member" DROP CONSTRAINT "Member_pkey";
ALTER TABLE "Session" DROP CONSTRAINT "Session_pkey";
ALTER TABLE "AuthIdentity" DROP CONSTRAINT "AuthIdentity_pkey";
ALTER TABLE "PhoneVerification" DROP CONSTRAINT "PhoneVerification_pkey";
ALTER TABLE "PasswordAttempt" DROP CONSTRAINT "PasswordAttempt_pkey";

DROP INDEX "Bookmark_memberId_postId_key";
DROP INDEX "Bookmark_memberId_memberSeq_key";
DROP INDEX "Bookmark_memberId_deletedAt_createdAt_idx";
DROP INDEX "Session_memberId_idx";
DROP INDEX "AuthIdentity_memberId_idx";

-- ---------------------------------------------------------------------------
-- Swap the columns in.
-- ---------------------------------------------------------------------------

ALTER TABLE "Bookmark" DROP COLUMN "memberId";
ALTER TABLE "Bookmark" RENAME COLUMN "memberId_int" TO "memberId";
ALTER TABLE "Bookmark" ALTER COLUMN "memberId" SET NOT NULL;

ALTER TABLE "Session" DROP COLUMN "memberId";
ALTER TABLE "Session" RENAME COLUMN "memberId_int" TO "memberId";
ALTER TABLE "Session" ALTER COLUMN "memberId" SET NOT NULL;

ALTER TABLE "AuthIdentity" DROP COLUMN "memberId";
ALTER TABLE "AuthIdentity" RENAME COLUMN "memberId_int" TO "memberId";
ALTER TABLE "AuthIdentity" ALTER COLUMN "memberId" SET NOT NULL;

ALTER TABLE "PostPlace" DROP COLUMN "placeId";
ALTER TABLE "PostPlace" RENAME COLUMN "placeId_int" TO "placeId";
ALTER TABLE "PostPlace" ALTER COLUMN "placeId" SET NOT NULL;

ALTER TABLE "BookmarkMemo" DROP COLUMN "placeId";
ALTER TABLE "BookmarkMemo" RENAME COLUMN "placeId_int" TO "placeId";
ALTER TABLE "BookmarkMemo" ALTER COLUMN "placeId" SET NOT NULL;

ALTER TABLE "BookmarkMemo" DROP COLUMN "bookmarkId";
ALTER TABLE "BookmarkMemo" RENAME COLUMN "bookmarkId_int" TO "bookmarkId";
ALTER TABLE "BookmarkMemo" ALTER COLUMN "bookmarkId" SET NOT NULL;

ALTER TABLE "Member" DROP COLUMN "id";
ALTER TABLE "Member" RENAME COLUMN "id_int" TO "id";
ALTER TABLE "Member" ALTER COLUMN "id" SET NOT NULL;

ALTER TABLE "Place" DROP COLUMN "id";
ALTER TABLE "Place" RENAME COLUMN "id_int" TO "id";
ALTER TABLE "Place" ALTER COLUMN "id" SET NOT NULL;

ALTER TABLE "Bookmark" DROP COLUMN "id";
ALTER TABLE "Bookmark" RENAME COLUMN "id_int" TO "id";
ALTER TABLE "Bookmark" ALTER COLUMN "id" SET NOT NULL;

-- The four tables whose ids nothing references: replace the text key outright.
-- Three of them are guaranteed empty by the guard above. AuthIdentity keeps its
-- rows, and its id is safe to renumber because nothing anywhere stores it — the
-- provider lookup goes through [provider, providerUserId], never the id.
ALTER TABLE "Session" DROP COLUMN "id";
ALTER TABLE "Session" ADD COLUMN "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "AuthIdentity" DROP COLUMN "id";
ALTER TABLE "AuthIdentity" ADD COLUMN "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "PhoneVerification" DROP COLUMN "id";
ALTER TABLE "PhoneVerification" ADD COLUMN "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "PasswordAttempt" DROP COLUMN "id";
ALTER TABLE "PasswordAttempt" ADD COLUMN "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY;

-- ---------------------------------------------------------------------------
-- Identity generation for the three remapped tables, seeded past the values
-- just written. Without setval the sequence begins at 1 and the next insert
-- collides with the oldest row.
-- ---------------------------------------------------------------------------

ALTER TABLE "Member" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('"Member"', 'id'), COALESCE((SELECT max("id") FROM "Member"), 0) + 1, false);

ALTER TABLE "Place" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('"Place"', 'id'), COALESCE((SELECT max("id") FROM "Place"), 0) + 1, false);

ALTER TABLE "Bookmark" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('"Bookmark"', 'id'), COALESCE((SELECT max("id") FROM "Bookmark"), 0) + 1, false);

-- ---------------------------------------------------------------------------
-- Primary keys, foreign keys, and indexes, rebuilt on the new columns.
-- ---------------------------------------------------------------------------

ALTER TABLE "Member" ADD CONSTRAINT "Member_pkey" PRIMARY KEY ("id");
ALTER TABLE "Place" ADD CONSTRAINT "Place_pkey" PRIMARY KEY ("id");
ALTER TABLE "Bookmark" ADD CONSTRAINT "Bookmark_pkey" PRIMARY KEY ("id");
ALTER TABLE "Session" ADD CONSTRAINT "Session_pkey" PRIMARY KEY ("id");
ALTER TABLE "AuthIdentity" ADD CONSTRAINT "AuthIdentity_pkey" PRIMARY KEY ("id");
ALTER TABLE "PhoneVerification" ADD CONSTRAINT "PhoneVerification_pkey" PRIMARY KEY ("id");
ALTER TABLE "PasswordAttempt" ADD CONSTRAINT "PasswordAttempt_pkey" PRIMARY KEY ("id");
ALTER TABLE "PostPlace" ADD CONSTRAINT "PostPlace_pkey" PRIMARY KEY ("postId", "placeId");
ALTER TABLE "BookmarkMemo" ADD CONSTRAINT "BookmarkMemo_pkey" PRIMARY KEY ("bookmarkId", "placeId");

ALTER TABLE "Bookmark" ADD CONSTRAINT "Bookmark_memberId_fkey"
  FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_memberId_fkey"
  FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuthIdentity" ADD CONSTRAINT "AuthIdentity_memberId_fkey"
  FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PostPlace" ADD CONSTRAINT "PostPlace_placeId_fkey"
  FOREIGN KEY ("placeId") REFERENCES "Place"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BookmarkMemo" ADD CONSTRAINT "BookmarkMemo_placeId_fkey"
  FOREIGN KEY ("placeId") REFERENCES "Place"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BookmarkMemo" ADD CONSTRAINT "BookmarkMemo_bookmarkId_fkey"
  FOREIGN KEY ("bookmarkId") REFERENCES "Bookmark"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE UNIQUE INDEX "Bookmark_memberId_postId_key" ON "Bookmark"("memberId", "postId");
CREATE UNIQUE INDEX "Bookmark_memberId_memberSeq_key" ON "Bookmark"("memberId", "memberSeq");
CREATE INDEX "Bookmark_memberId_deletedAt_createdAt_idx" ON "Bookmark"("memberId", "deletedAt", "createdAt");
CREATE INDEX "Session_memberId_idx" ON "Session"("memberId");
CREATE INDEX "AuthIdentity_memberId_idx" ON "AuthIdentity"("memberId");

-- Untouched by the column swaps, listed so a reader can confirm nothing was
-- lost: Member_phoneHash_idx, Member_phoneHash_live_key (the account-merge
-- invariant — one live account per phone number), Member_withdrawnAt_idx,
-- Member_phone_pair_check, AuthIdentity_provider_providerUserId_idx,
-- AuthIdentity_provider_providerUserId_live_key, Place_name_address_key,
-- Session_tokenHash_key, Session_expiresAt_idx, PostPlace_placeId_idx,
-- BookmarkMemo_placeId_idx, and the PhoneVerification/PasswordAttempt indexes.
-- None of them names a column this migration replaced, so all survive as-is.
